### ISSUE TITLE
Search bar should be visible on mobile

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-docs-ui#46]
Being able to search on mobile would be really beneficial since navigation is a bit more difficult than on desktop. So, being able to jump between pages using the search would provide a better experience on mobile.

Here's a rough draft:

![102711115-a33c0480-42b7-11eb-8366-da0bf3894cc1](https://user-images.githubusercontent.com/333276/102711464-42fa9200-42ba-11eb-908f-509e3309e8e0.png)

In the above screenshot, I've also replace the hamburger menu with an explicit "Menu" button but we can leave it for another issue.

**Comment by mojavelinux** [comment]
I think this could be as basic (in the end, not necessarily in time spent figuring it out) as placing the search box using absolute position / negative margins into the search bar region. Since the site title could get in the way, it probably has to go to the right in what space is available.

It might be necessary to shorten the site title on mobile if not enough space is available.

The alternative would be to have the search expand when you click the search icon, but that is going to take a lot more work.

**Comment by mojavelinux** [comment]
Another idea is to have the search icon open the menu and focus the search box that is inside of it. That would probably be the quickest solution, so perhaps consider it as an interim step.

**Comment by mojavelinux** [comment]
I think we should take this in two stages. First, we should just enable the search bar where it is, adjusting the styles so it's at least functional. In a follow-up issue, we should think about where we actually want the search bar to appear on mobile and what behavior it should have. That may require moving it and/or adding additional HTML / JavaScript / and CSS.

cc: @graphitefriction

**Comment by mojavelinux** [comment]
FYI, the reason I disabled it is only because I hadn't yet had the chance to add the necessary styles to position it.
