### ISSUE TITLE
Replace the hamburger menu with an explicit "Menu" button

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-docs-ui#47]
Hamburger menus are everywhere but I think there's an agreement that they are not the most accessible component.

Instead, we would replace it with an explicit "Menu" button:

![102711115-a33c0480-42b7-11eb-8366-da0bf3894cc1](https://user-images.githubusercontent.com/333276/102711484-70474000-42ba-11eb-840d-bfe79a4851e7.png)

**Comment by mojavelinux** [comment]
I am not in agreement that there is a consensus that these menus aren't accessible. In fact, what I observe is exactly the opposite. These menus are becoming so much a part of the human experience that they are universally understood (at least for those who have access to technology...and even those who don't through culture). Unless there is a definitive study and recommendation from an accessibility group that we should take action now, I'm not interested in trying to redefine in our own docs site a pattern that is so well understood.

**Comment by Mogztter** [comment]
A good one about menu: https://youtu.be/Nl3OYHo2_b8?t=101
Luke's moto "obvious always win" really makes sense to me: https://www.lukew.com/ff/entry.asp?1945

> These menus are becoming so much a part of the human experience that they are universally understood (at least for those who have access to technology...and even those who don't through culture).

A counter-point about universally understood: "Obvious icons are not always universal icons".
A good example:

![DwfAw4CVYAEV_eN](https://user-images.githubusercontent.com/333276/102775304-def4ce00-438c-11eb-9acc-b2017d8933ef.jpg)

It's tempting to think that magnifying glass is universally understood but I guess it's not.

> Unless there is a definitive study and recommendation from an accessibility group that we should take action now, I'm not interested in trying to redefine in our own docs site a pattern that is so well understood.

We can keep the hamburger icon but adding a label makes it even more obvious.
I think that adding `aria-label` on the hamburger could also improve accessibility.

Another key point is don't hide *actions* and keep them in the "thumb zone": https://www.smashingmagazine.com/2019/08/bottom-navigation-pattern-mobile-web-pages/

In our case, this does not really apply because we are using it for navigation.

**Comment by mojavelinux** [comment]
This conversation just really feels out of scope and distracting to what we're trying to accomplish. We're not about defining accessibility for the web. If there are solid patterns to follow, I'm open to that. But I'm not interested in either a) defining them or b) defending them.

I could get behind the addition of aria-label. I would also consider the icon + label that redhat.com uses. (Though we use other icons without labels, so it seems strange to do it just for this one).

I'll point out that Bootstrap, Bulma, and Foundation all use the hamburger menu exactly how we are using it. So it's a stretch to say they are doing it wrong. And if they are, that's where the debate should be.

**Comment by Mogztter** [comment]
> I could get behind the addition of aria-label. I would also consider the icon + label that redhat.com uses.

👍 
I've seen this pattern a few times:

```html
<button type="button" aria-expanded="false" aria-label="Toggle navigation"></button>
```

> If there are solid patterns to follow, I'm open to that. But I'm not interested in either a) defining them or b) defending them.

I don't know... the hamburger menu is ubiquitous and often used without label but it does not mean that this is how it should be done.
I'm not trying to define accessibility for the web but I can't help thinking that icon + label gives an extra clue. I think this is empathic design: "you don't what this icon means? it means 'Menu'", rather than "you don't know what this icon means, go figure". And if you already know, good for you 😄 

> I'll point out that Bootstrap, Bulma, and Foundation all use the hamburger menu exactly how we are using it. So it's a stretch to say they are doing it wrong. And if they are, that's where the debate should be.

I get your point even in this case we are not using any CSS framework.

**Comment by mojavelinux** [comment]
It's very rare for me to see the hamburger nav menu displayed with anything other than the three lines. It's very safe to say that it has become ubiquitous and I see no reason for us to deviate from that pattern. However, I am seeing frequent  use of the `aria-label` attribute with text similar to "Toggle menu", so I'm going to proceed with adding that metadata to resolve this issue.

**Comment by mojavelinux** [comment]
I'm going to apply this change upstream, then pull it in to resolve it.
